CREATE TABLE IF NOT EXISTS fiscal_jobs (
    id BIGINT NOT NULL AUTO_INCREMENT,
    empresa_id BIGINT NOT NULL,
    documento_id BIGINT NOT NULL,
    idempotencia_id BIGINT NOT NULL,
    tipo VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL,
    ator VARCHAR(320) NOT NULL,
    correlation_id VARCHAR(100) NOT NULL,
    tentativas INT NOT NULL DEFAULT 0,
    max_tentativas INT NOT NULL DEFAULT 5,
    proxima_tentativa_em DATETIME(6) NOT NULL,
    iniciado_em DATETIME(6) NULL,
    finalizado_em DATETIME(6) NULL,
    ultimo_erro VARCHAR(500) NULL,
    criado_em DATETIME(6) NOT NULL,
    versao BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    CONSTRAINT uk_fiscal_job_idempotencia UNIQUE (idempotencia_id),
    CONSTRAINT fk_fiscal_job_empresa FOREIGN KEY (empresa_id) REFERENCES empresas (id),
    CONSTRAINT fk_fiscal_job_documento FOREIGN KEY (documento_id) REFERENCES notas_fiscais (id),
    CONSTRAINT fk_fiscal_job_idempotencia FOREIGN KEY (idempotencia_id) REFERENCES fiscal_idempotency (id),
    INDEX idx_fiscal_job_fila (status, proxima_tentativa_em),
    INDEX idx_fiscal_job_documento (documento_id)
) ENGINE=InnoDB;
