CREATE TABLE IF NOT EXISTS produto_configuracoes_fiscais (
    id BIGINT NOT NULL AUTO_INCREMENT,
    produto_id BIGINT NOT NULL,
    empresa_id BIGINT NOT NULL,
    versao INT NOT NULL,
    vigencia_inicio DATE NOT NULL,
    vigencia_fim DATE,
    ncm CHAR(8) NOT NULL,
    cest CHAR(7),
    origem CHAR(1) NOT NULL,
    unidade_comercial VARCHAR(6) NOT NULL,
    unidade_tributavel VARCHAR(6) NOT NULL,
    gtin VARCHAR(14),
    cfop_padrao CHAR(4) NOT NULL,
    csosn CHAR(3),
    cst_icms CHAR(3),
    cst_ipi CHAR(2),
    cst_pis CHAR(2) NOT NULL,
    cst_cofins CHAR(2) NOT NULL,
    cst_ibs_cbs CHAR(3),
    cclass_trib CHAR(6),
    confirmado_responsavel BOOLEAN NOT NULL,
    criado_por VARCHAR(320) NOT NULL,
    criado_em DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_produto_fiscal_versao UNIQUE (produto_id, versao),
    CONSTRAINT fk_produto_fiscal_produto FOREIGN KEY (produto_id) REFERENCES produto (id),
    CONSTRAINT fk_produto_fiscal_empresa FOREIGN KEY (empresa_id) REFERENCES empresas (id),
    INDEX idx_produto_fiscal_vigencia (produto_id, vigencia_inicio, vigencia_fim),
    INDEX idx_produto_fiscal_empresa (empresa_id)
) ENGINE=InnoDB;
