import { LegalShell } from "@/components/legal/legal-shell";
import { pageMetadata } from "@/lib/seo";
export const metadata = pageMetadata({ title: "Cancelamento e Reembolsos", description: "Informações sobre planos, assinaturas, cancelamento, cobrança e reembolsos da Gevyro.", path: "/cancelamento-reembolsos" });
export default function CancelamentoPage() { return <LegalShell title="Cancelamento, Assinaturas e Reembolsos" description="Condições confirmadas no sistema e decisões comerciais que ainda precisam ser formalizadas antes da produção.">
  <h2>1. Planos e cobrança</h2><p>Os planos Básico (R$ 79,90/mês), Pro (R$ 149,90/mês) e Premium (R$ 299,90/mês) são apresentados como assinaturas mensais recorrentes. A cobrança é concluída no checkout da Stripe. O resumo final, impostos eventualmente aplicáveis e meio de pagamento são exibidos no ambiente do processador antes da confirmação.</p>
  <h2>2. Período experimental</h2><p>O frontend anuncia 30 dias de teste sem cartão, e o backend contém plano experimental. <strong>PENDÊNCIA: confirmar quando o período começa, elegibilidade, recursos liberados e comportamento ao término.</strong></p>
  <h2>3. Renovação e inadimplência</h2><p>A assinatura pode renovar automaticamente a cada período mensal até o cancelamento. O backend reconhece estados informados pela Stripe e o acesso não deve ser decidido isoladamente pelo navegador. <strong>PENDÊNCIA: definir comunicações de renovação, tentativas de cobrança e prazo de regularização.</strong></p>
  <h2>4. Cancelamento</h2><p>O backend disponibiliza criação de sessão do portal de cobrança para assinaturas existentes. Por esse portal, o usuário poderá administrar a assinatura conforme as configurações efetivamente habilitadas na Stripe. <strong>PENDÊNCIA: confirmar se o cancelamento é imediato ou ao fim do ciclo e exibir essa informação antes da confirmação.</strong></p>
  <h2>5. Reembolso e arrependimento</h2><p>Não foi encontrada no projeto uma política comercial de reembolso implementada. Isso não elimina direitos obrigatórios. Solicitações relacionadas ao direito de arrependimento em contratação eletrônica serão avaliadas conforme o Código de Defesa do Consumidor e as circunstâncias legais aplicáveis. <strong>PENDÊNCIA: aprovar política de reembolso com assessoria jurídica e configurar o procedimento operacional.</strong></p>
  <h2>6. Dados após encerramento</h2><p>Cancelar a assinatura não equivale automaticamente a excluir a conta. Retenção e exclusão dependem de obrigações legais, fiscais, segurança e exercício de direitos. Solicitações podem ser iniciadas na área de Privacidade e Dados ou pelo contato oficial.</p>
  <h2>7. Atendimento</h2><p>Consulte a página de <a href="/contato">Contato</a> e informe o e-mail da conta e o assunto, sem enviar número completo de cartão, senha ou token.</p>
</LegalShell>; }
